language: node_js
sudo: false
node_js:
  - "6"
install:
  - travis_retry npm install
notifications:
  email: false
cache:
  directories:
    - node_modules
branches:
  only:
    - master
env:
  global:
  - GOVUK_WEBSITE_ROOT: 'https://www.gov.uk'
  matrix:
  - TEST_CMD: test:unit
  - TEST_CMD: shell:cheapseats
  - TEST_CMD: test:functional:ci
# Add back in when we're out of emergency mode
#   - TEST_CMD: shell:cheapseats:--range:0..50
#   - TEST_CMD: shell:cheapseats:--range:51..100
#   - TEST_CMD: shell:cheapseats:--range:101..150
#   - TEST_CMD: shell:cheapseats:--range:151..
#
script: "npm run $TEST_CMD"
matrix:
  fast_finish: true
